### ISSUE TITLE
WebGL Build Error

### ISSUE THREAD

**Issue by MohammadMDSA** [mkrebser/GPUInstance#19]
Hey,

Thank you for the awesome package.
In my WebGL build in the initialization I get the error `Kernel 'UpdateBuffers' not found`.
Also in the updates I get `Error, must invoke function from main thread!`. Since there is only one thread in WebGL, I commented this exception out but got other exceptions instead.

Is there something I am not doing write or there should be modifications applied for the package to work with WebGL?

**Comment by mkrebser** [comment]
I have never tested this with webGL in mind. It is mainly built with desktop/potentially consoles or other hardware which has dedicated graphics cards.

I do not know what webGL version you are using but here is Unity's page that goes over webGL limitations per version https://docs.unity3d.com/Manual/webgl-graphics.html

It may also be the hardware you are running does not support shader model 5.0. Specifically, you need hardware that is compatible with compute shaders https://docs.unity3d.com/Manual/class-ComputeShader.html

**Comment by MohammadMDSA** [comment]
Thanks. I figured that OpenGL supports only a limited number of bindings and the shader used in the library is too much for the OpenGL platform.

So wherever you decide to target WebGL or OpenGL platforms, consider reducing the number of bindings.
