### ISSUE TITLE
Enabling/Disabling Animations For Certain Bones

### ISSUE THREAD

**Issue by CybeRockStudio** [mkrebser/GPUInstance#2]
Hi There

Really Powerful Tool You Have Created Here I'm Very Happy With How Stable It Is

My Question Is How Can I Enable/Disable Some Bones Per Animation To Achieve Some Sort Of Animation Blending

Kind Regards & Thanks For Taking Time To Answer Me

**Comment by CybeRockStudio** [comment]
And Yes,


How Do I Change Animations At Runtime?

**Comment by CybeRockStudio** [comment]
Hi There After About 3 Hrs Digging I Found Answers To My Solutions 💯

**Comment by CybeRockStudio** [comment]
one last question if i may ask

is animation transitioning implementable witht his approach?

**Comment by CybeRockStudio** [comment]
and if it is can you give me a guide on how to do it?

**Comment by mkrebser** [comment]
You would have to refactor the compute shaders to implement blending.

You would need a second set of animation parameters (animation Id, speed,
looping) and blend parameters.

In the compute shaders you would calculate two local bone animations - and
lerp between them

**Comment by CybeRockStudio** [comment]
hey thanks for the guidance
