### ISSUE TITLE
Camera Controls Wonky (always rotating with mouse)

### ISSUE THREAD

**Issue by najak3d** [mkrebser/GPUInstance#4]
I created a "MainCamera" prefab, with the following adjusted settings on "CameraFreeFly" script:

Move Speed: 4
Sensitivity 4
Rotate When Down:   Mouse1     (same as for Unity editor)
Sprint Multiplier:  7

The biggest need here is for "Mouse1" rotation (right mouse button) -- so that the camera isn't constantly rotating.
And the slower default speed with "7" Sprint, allows for fine-tuned motion, and fast motion (both needed for exploring the demo)

Then use this MainCamera Prefab in ALL demo scenes, and so if a user wants to adjust the Camera settings, they need only change the values on the prefab.

So this issue is just a suggestion to update to using a Camera prefab, with better settings (like those above).

**Comment by mkrebser** [comment]
the camera really isn't meant to be used for your games, it's kept intentionally as simple as possible just for looking at the demo scenes

Some of the demos are really large scenes, so a sprint is added. But I wouldn't expect anyone to know about the hotkeys when they are first opening the scene
